### ISSUE TITLE
Considering Additions

### ISSUE THREAD

**Issue by jacoby** [hacklafayette/newsletter#1]
Markdown to HTML?
HTML Mail?
Automated Sending?

**Comment by funnelfiasco** [comment]
Automated sending is a quick reject because that would require me to have it ready to send by a particular time, which sometimes happens and sometimes doesn't.

The way it's written right now is a lazy markdown that GitHub and Meetup render as desired but Pandoc doesn't. I can change the way I construct it, but to what end? The two forms where people will consume it already work.

**Comment by jacoby** [comment]
If and when the newsletter gets other uses and tools, they'll get their own issues.
